
  # version attribute removed as it is obsolete
services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "5001:5000"
    env_file:
      - ./api/.env
    volumes:
      - ./api:/app
      - /app/node_modules
  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - ./web/.env
    volumes:
      - ./web:/app
      - /app/node_modules
    depends_on:
      - api